variable pgsql_admin_login {}
variable pgsql_admin_password {}
variable pgsql_fqdn {}
variable redis_cache_host {}
variable redis_cache_password {}
variable pgvector_username {}
variable pgvector_password {}
variable pgvector_fqdn {}
variable dify_image_api_acr {}
variable dify_image_web_acr {}
variable dify_image_sandbox_acr {}